name: Build and publish Docker distributions to Github Container Registry ghcr.io

on:
  push:
    branches:
      - master
      - version-*
    paths:
      - gradle.properties


jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Get branch name
        id: branch
        run: echo ::set-output name=branch_name::${GITHUB_REF#refs/*/}

      - id: version
        name: resolve app version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: package.json
          prop_path: version

      - name: Show release version
        run: echo ${{ steps.version.outputs.prop }}

      - name: set up docker buildx plugin
        uses: docker/setup-buildx-action@v1

      - name: log in to github container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build image & push to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
          tags: ghcr.io/${{ github.repository }}:${{ steps.version.outputs.prop }}
          labels: com.exactpro.th2.${{ steps.repo.outputs.REPOSITORY_NAME }}=${{ steps.version.outputs.prop }}
